// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBExlWR-RuYcNvYs5nj89JcDBFeaAFFBMQ',
    appId: '1:450201639046:web:8ee21e9dca83d948fa9907',
    messagingSenderId: '450201639046',
    projectId: 'notes-appp-ff868',
    authDomain: 'notes-appp-ff868.firebaseapp.com',
    storageBucket: 'notes-appp-ff868.firebasestorage.app',
    measurementId: 'G-E3059K47PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9zNzRXsag7ZgzfFwO8BXHnwoUynVf_EE',
    appId: '1:450201639046:android:a9448a64128892eefa9907',
    messagingSenderId: '450201639046',
    projectId: 'notes-appp-ff868',
    storageBucket: 'notes-appp-ff868.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvNfwBxqyp25wPvUplFjLs0ZwJ9I56MOQ',
    appId: '1:450201639046:ios:7a2a712914179177fa9907',
    messagingSenderId: '450201639046',
    projectId: 'notes-appp-ff868',
    storageBucket: 'notes-appp-ff868.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBExlWR-RuYcNvYs5nj89JcDBFeaAFFBMQ',
    appId: '1:450201639046:web:8054c2e827d2755afa9907',
    messagingSenderId: '450201639046',
    projectId: 'notes-appp-ff868',
    authDomain: 'notes-appp-ff868.firebaseapp.com',
    storageBucket: 'notes-appp-ff868.firebasestorage.app',
    measurementId: 'G-HR9BJCRZG9',
  );
}
